<?php
require_once __DIR__ . '/includes/auth.php';
$pageTitle = 'Active Login Sessions · FieldPlx';
$pageDescription = 'Review and revoke active device sessions';
$settingsActivePage = 'team';
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['team_settings_csrf'])) $_SESSION['team_settings_csrf'] = bin2hex(random_bytes(32));
$csrfToken = (string)$_SESSION['team_settings_csrf'];
$targetUserId = isset($_GET['user_id']) ? max(0,(int)$_GET['user_id']) : 0;
require __DIR__ . '/includes/header.php';
require_once __DIR__ . '/includes/toast.php';
?>
<style>
.als-page{max-width:980px;margin:0 auto;padding:20px 24px 44px}.als-back{display:inline-flex;margin-bottom:12px;color:#4b8d28;text-decoration:none;font-size:11px}.als-page h1{margin:0 0 24px;color:#0b1933;font-size:30px}.als-page h2{margin:0 0 4px;color:#0b3142;font-size:17px}.als-sub{margin:0 0 18px;color:#6f7b90;font-size:11px}.als-card{border:1px solid #dce4eb;border-radius:8px;background:#fff;overflow:hidden}.als-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;border-bottom:1px solid #dfe6eb}.als-card-head strong{font-size:12px;color:#0b3142}.als-count{display:inline-grid;place-items:center;min-width:20px;height:18px;padding:0 6px;border-radius:999px;background:#edf0f1;color:#60727e;font-size:9px}.als-email{margin-top:2px;color:#6f7b90;font-size:9px}.als-btn{min-height:32px;display:inline-flex;align-items:center;justify-content:center;padding:0 12px;border:1px solid #d9e2e9;border-radius:8px;background:#fff;color:#df4f3f;font:inherit;font-size:10px;font-weight:700;cursor:pointer}.als-row{display:grid;grid-template-columns:36px minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px 14px;border-bottom:1px solid #e7ecf0}.als-row:last-child{border-bottom:0}.als-icon{width:30px;height:30px;display:grid;place-items:center;border-radius:7px;background:#f1f0ed;color:#1d4655}.als-name{font-size:11px;font-weight:700;color:#183848}.als-meta{margin-top:3px;color:#71808d;font-size:9px}.als-online{color:#2f8c25}.als-empty,.als-loading{padding:28px;text-align:center;color:#6f7b90;font-size:11px}.als-btn.loading{opacity:.65;pointer-events:none}.als-btn.loading:before{content:"";width:11px;height:11px;margin-right:6px;border:2px dotted currentColor;border-radius:50%;animation:s .75s linear infinite}@keyframes s{to{transform:rotate(360deg)}}
@media(max-width:640px){.als-page{padding:15px}.als-card-head{align-items:flex-start;flex-direction:column}.als-row{grid-template-columns:32px 1fr}.als-row .als-btn{grid-column:2;justify-self:start}}
</style>
<div class="als-page"><a class="als-back" href="team.php">‹ &nbsp; Manage team</a><h1>Active Login Sessions</h1><div id="sessionContent" class="als-loading">Loading active sessions...</div></div>
<script>
(function(){'use strict';var csrf=<?= json_encode($csrfToken,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,api='api/team.php',userId=<?= (int)$targetUserId ?>;function E(id){return document.getElementById(id)}function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function toast(t,m){if(window.fieldplxToast)window.fieldplxToast(t,m)}function req(fd){fd.append('csrf_token',csrf);return fetch(api,{method:'POST',body:fd,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}).then(function(r){return r.text().then(function(x){var d;try{d=JSON.parse(x)}catch(e){throw new Error('Invalid server response.')}if(!r.ok||!d.success)throw new Error(d.message||'Request failed.');return d})})}function ago(v){if(!v)return 'Unknown';var d=new Date(String(v).replace(' ','T')),n=(Date.now()-d.getTime())/1000;if(isNaN(n))return v;if(n<60)return 'just now';if(n<3600)return Math.floor(n/60)+' min. ago';if(n<86400)return Math.floor(n/3600)+' hr. ago';return Math.floor(n/86400)+' day(s) ago'}function device(r){var n=String(r.device_name||'').trim();return n||String(r.platform||'Other').replace(/^./,function(c){return c.toUpperCase()})}
function load(){var f=new FormData();f.append('action','sessions');f.append('user_id',String(userId));req(f).then(function(d){var m=d.member||{},rows=d.sessions||[],name=((m.first_name||'')+' '+(m.last_name||'')).trim();var h='<h2>'+esc(name||'Team member')+'</h2><p class="als-sub">These devices are currently signed in to FieldPlx as '+esc(name||'this team member')+'. Sign out anything that looks unfamiliar.</p><section class="als-card"><div class="als-card-head"><div><strong>Active sessions <span class="als-count">'+rows.length+'</span></strong><div class="als-email">'+esc(m.email||'')+'</div></div><button class="als-btn" id="signAll" '+(!rows.length?'disabled':'')+'>Sign out all sessions</button></div>';
if(!rows.length)h+='<div class="als-empty">No active device sessions found.</div>';else rows.forEach(function(r){h+='<div class="als-row"><div class="als-icon">▣</div><div><div class="als-name">'+esc(device(r))+'</div><div class="als-meta">'+esc(String(r.platform||'Other'))+' · IP '+esc(r.last_ip_address||'Unknown')+' · <span class="als-online">●</span> '+esc(ago(r.last_seen_at||r.created_at))+'</div></div><button class="als-btn" data-sign="'+Number(r.id)+'">Sign out</button></div>'});h+='</section>';E('sessionContent').className='';E('sessionContent').innerHTML=h;var all=E('signAll');if(all)all.onclick=function(){sign('signout_all',0,this)};document.querySelectorAll('[data-sign]').forEach(function(b){b.onclick=function(){sign('signout_session',Number(b.getAttribute('data-sign')),b)}})}).catch(function(e){E('sessionContent').innerHTML='<div class="als-empty">Unable to load active sessions.</div>';toast('error',e.message)})}
function sign(action,id,b){var f=new FormData();f.append('action',action);f.append('user_id',String(userId));if(id)f.append('device_id',String(id));b.disabled=true;b.classList.add('loading');req(f).then(function(d){toast('success',d.message);load()}).catch(function(e){toast('error',e.message);b.disabled=false;b.classList.remove('loading')})}if(userId<=0){E('sessionContent').innerHTML='<div class="als-empty">No team member selected.</div>'}else load();})();
</script>
<?php require __DIR__ . '/includes/footer.php'; ?>
