<?php
require_once __DIR__ . '/includes/auth.php';
$pageTitle = 'Invite Team Member · FieldPlx';
$pageDescription = 'Invite or update a FieldPlx team member';
$settingsActivePage = 'team';
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['team_settings_csrf'])) $_SESSION['team_settings_csrf'] = bin2hex(random_bytes(32));
$csrfToken = (string)$_SESSION['team_settings_csrf'];
$editUserId = isset($_GET['user_id']) ? max(0,(int)$_GET['user_id']) : 0;
require __DIR__ . '/includes/header.php';
require_once __DIR__ . '/includes/toast.php';
?>
<style>
.tmi-page{display:grid;grid-template-columns:250px minmax(0,1fr);gap:28px;max-width:1320px;margin:0 auto;padding:8px 0 70px}.tmi-main{min-width:0}.tmi-back{display:inline-flex;margin-bottom:14px;color:#4b8d28;text-decoration:none;font-size:11px}.tmi-title{margin:0 0 20px;color:#0b1933;font-size:30px}.tmi-card{margin-bottom:14px;padding:16px;border:1px solid #dce4eb;border-radius:9px;background:#fff}.tmi-card h2{margin:0 0 12px;color:#0b3142;font-size:19px}.tmi-profile{display:flex;align-items:center;gap:10px;margin-bottom:12px}.tmi-avatar{width:52px;height:52px;display:grid;place-items:center;border-radius:50%;overflow:hidden;background:#173d49;color:#fff;font-size:21px}.tmi-avatar img{width:100%;height:100%;object-fit:cover}.tmi-btn{min-height:34px;display:inline-flex;align-items:center;justify-content:center;padding:0 12px;border:1px solid #d9e2e9;border-radius:8px;background:#fff;color:#2f7f24;font:inherit;font-size:11px;font-weight:700;cursor:pointer;text-decoration:none}.tmi-btn.primary{background:#2f8c25;border-color:#2f8c25;color:#fff}.tmi-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tmi-field{margin-bottom:10px}.tmi-field.full{grid-column:1/-1}.tmi-field label{display:block;margin:0 0 5px;color:#183b4d;font-size:10px;font-weight:700}.tmi-input,.tmi-select{width:100%;height:40px;padding:0 12px;border:1px solid #d9e2e9;border-radius:8px;background:#fff;color:#193649;font:inherit;font-size:11px;outline:none}.tmi-input:focus,.tmi-select:focus{border-color:#74b824;box-shadow:0 0 0 2px rgba(116,184,36,.12)}.tmi-check{display:flex;align-items:flex-start;gap:8px;font-size:11px;color:#294b5b}.tmi-divider{height:1px;margin:14px 0;background:#e7ecf0}.tmi-preset-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tmi-preset{padding:12px;border:1px solid #dde5ea;border-radius:8px;cursor:pointer}.tmi-preset.active{border-color:#74b824;box-shadow:0 0 0 1px #74b824}.tmi-preset strong{font-size:12px;color:#0b3142}.tmi-preset p{margin:6px 0 0;color:#6f7b90;font-size:10px;line-height:1.4}.tmi-perm-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:14px 0 8px}.tmi-perm-head h3{margin:0;color:#0b3142;font-size:13px}.tmi-perms{display:grid;grid-template-columns:1fr 1fr;gap:7px 16px}.tmi-perm{display:flex;align-items:flex-start;gap:7px;padding:5px 0;font-size:10px;color:#294b5b}.tmi-actions{position:sticky;bottom:0;z-index:50;display:flex;justify-content:flex-end;gap:8px;margin:16px -1px -1px;padding:9px 0;background:rgba(255,255,255,.96)}.tmi-note{padding:10px;border-radius:8px;background:#f6f8fa;color:#6f7b90;font-size:10px;line-height:1.5}.tmi-loading{padding:30px;text-align:center;color:#6f7b90}.tmi-btn.loading{opacity:.65;pointer-events:none}.tmi-btn.loading:before{content:"";width:12px;height:12px;margin-right:7px;border:2px dotted currentColor;border-radius:50%;animation:tmiSpin .75s linear infinite}@keyframes tmiSpin{to{transform:rotate(360deg)}}
@media(max-width:980px){.tmi-page{grid-template-columns:1fr;padding:14px}.tmi-page>aside{display:none}}@media(max-width:680px){.tmi-grid,.tmi-preset-grid,.tmi-perms{grid-template-columns:1fr}}
</style>
<div class="tmi-page">
 <aside><?php require __DIR__ . '/includes/settings-nav.php'; ?></aside>
 <main class="tmi-main">
  <a class="tmi-back" href="team.php">‹ &nbsp; Manage team</a>
  <h1 class="tmi-title" id="pageHeading"><?= $editUserId > 0 ? 'Edit team member' : 'Invite a new member' ?></h1>
  <div id="loading" class="tmi-loading">Loading team settings...</div>
  <form id="memberForm" enctype="multipart/form-data" style="display:none">
   <input type="hidden" name="action" value="save_member"><input type="hidden" name="user_id" value="<?= (int)$editUserId ?>"><input type="hidden" name="permissions_mode" id="permissionsMode" value="role"><input type="hidden" name="save_and_assign" id="saveAndAssign" value="0">
   <section class="tmi-card"><h2>Personal info</h2><div class="tmi-profile"><div class="tmi-avatar" id="avatarPreview">U</div><label class="tmi-btn">Upload Image<input type="file" name="avatar" id="avatarInput" accept="image/png,image/jpeg,image/webp" hidden></label></div><div class="tmi-grid"><div class="tmi-field"><label>Full name *</label><input class="tmi-input" name="full_name" id="fullName" required placeholder="Full name"></div><div class="tmi-field"><label>Email address *</label><input class="tmi-input" type="email" name="email" id="email" required placeholder="Email address"></div><div class="tmi-field"><label>Mobile phone number</label><input class="tmi-input" name="phone" id="phone" placeholder="Mobile phone number"></div><div class="tmi-field"><label>Employee code</label><input class="tmi-input" name="employee_code" id="employeeCode" placeholder="Optional employee code"></div><div class="tmi-field"><label>Job title</label><input class="tmi-input" name="job_title" id="jobTitle" placeholder="Job title"></div><div class="tmi-field"><label>Labour cost per hour</label><input class="tmi-input" type="number" min="0" step="0.01" name="labor_rate" id="laborRate" placeholder="0.00"></div></div><div class="tmi-note">Your current FieldPlx database stores the team member's account, phone, role, labour rate, avatar and permissions. Address and invitation-language fields are not present in the current schema, so this page does not invent unsupported database fields.</div></section>
   <section class="tmi-card"><h2>Permissions</h2><label class="tmi-check"><input type="checkbox" name="is_tenant_admin" id="isAdmin" value="1"><span><strong>Make administrator</strong><br><small>Administrators can access all account areas permitted by the tenant.</small></span></label><div class="tmi-divider"></div><div class="tmi-field"><label>Role</label><select class="tmi-select" name="role_id" id="roleSelect"><option value="0">No role</option></select></div><h3 style="margin:12px 0 7px;font-size:13px;color:#0b3142">Preset permission levels</h3><p style="margin:0 0 10px;color:#6f7b90;font-size:10px">Start with a preset and customize individual permissions when needed.</p><div class="tmi-preset-grid"><div class="tmi-preset" data-preset="field"><strong>Field crew</strong><p>Schedule, jobs, visits, time and notes focused access.</p></div><div class="tmi-preset" data-preset="senior"><strong>Senior field crew</strong><p>Field crew access plus customers, quotes, invoices and payments.</p></div><div class="tmi-preset" data-preset="lead"><strong>Crew lead</strong><p>Broader create/edit access for jobs, team scheduling and customers.</p></div><div class="tmi-preset" data-preset="manager"><strong>Manager</strong><p>Business operations, reports and wider management access.</p></div><div class="tmi-preset" data-preset="custom"><strong>Custom</strong><p>Choose individual permissions below.</p></div></div><div class="tmi-perm-head"><h3>Custom permissions</h3><span style="font-size:10px;color:#6f7b90" id="permCount"></span></div><div class="tmi-perms" id="permissionList"></div></section>
   <div class="tmi-actions"><a href="team.php" class="tmi-btn">Cancel</a><button type="button" class="tmi-btn" id="saveMember">Save Member</button><button type="button" class="tmi-btn primary" id="saveAssign">Save and Assign</button></div>
  </form>
 </main>
</div>
<script>
(function(){'use strict';var csrf=<?= json_encode($csrfToken,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,api='api/team.php',userId=<?= (int)$editUserId ?>,permissions=[],member=null;
function E(id){return document.getElementById(id)}function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function toast(t,m){if(window.fieldplxToast)window.fieldplxToast(t,m)}function req(fd){fd.append('csrf_token',csrf);return fetch(api,{method:'POST',body:fd,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}).then(function(r){return r.text().then(function(x){var d;try{d=JSON.parse(x)}catch(e){throw new Error('Invalid server response.')}if(!r.ok||!d.success)throw new Error(d.message||'Request failed.');return d})})}
function post(a){var f=new FormData();f.append('action',a);return f}function label(p){return (p.description||p.permission_code||'Permission').replace(/^View /,'View ')}
function renderPerms(selected){var set={};(selected||[]).forEach(function(id){set[Number(id)]=1});E('permissionList').innerHTML=permissions.map(function(p){return '<label class="tmi-perm"><input type="checkbox" name="permission_ids[]" value="'+Number(p.id)+'" data-code="'+esc(p.permission_code)+'" '+(set[Number(p.id)]?'checked':'')+'><span>'+esc(label(p))+'<br><small style="color:#82909a">'+esc(p.permission_code)+'</small></span></label>'}).join('');countPerms()}
function countPerms(){var n=document.querySelectorAll('#permissionList input:checked').length;E('permCount').textContent=n+' selected'}
function choosePreset(name){document.querySelectorAll('.tmi-preset').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-preset')===name)});var boxes=document.querySelectorAll('#permissionList input');E('permissionsMode').value=name==='custom'?'custom':'custom';boxes.forEach(function(b){var c=String(b.getAttribute('data-code')||''),on=false;if(name==='field')on=/^(jobs|visits|scheduling|workforce|time|notes|expenses)\./.test(c)&&!/delete/.test(c);else if(name==='senior')on=/^(jobs|visits|scheduling|workforce|time|notes|expenses|clients|quotes|invoices|payments)\./.test(c)&&!/delete/.test(c);else if(name==='lead')on=/^(jobs|visits|scheduling|workforce|time|notes|expenses|clients|quotes|invoices|payments|requests|teams)\./.test(c);else if(name==='manager')on=!/^(settings|roles)\.(delete)/.test(c);else return;b.checked=on});countPerms()}
function meta(){var f=post('meta');return req(f).then(function(d){permissions=d.permissions||[];var rs=d.roles||[],h='<option value="0">No role</option>';rs.forEach(function(r){h+='<option value="'+Number(r.id)+'">'+esc(r.name)+'</option>'});E('roleSelect').innerHTML=h;renderPerms([]);if(userId>0){var x=post('get_member');x.append('user_id',String(userId));return req(x).then(function(m){member=m.member||{};E('fullName').value=((member.first_name||'')+' '+(member.last_name||'')).trim();E('email').value=member.email||'';E('phone').value=member.phone||'';E('employeeCode').value=member.employee_code||'';E('jobTitle').value=member.job_title||'';E('laborRate').value=member.labor_rate||'';E('roleSelect').value=String(member.role_id||0);E('isAdmin').checked=Number(member.is_tenant_admin||0)===1;if(member.avatar_path)E('avatarPreview').innerHTML='<img src="'+esc(member.avatar_path)+'" alt="">';else E('avatarPreview').textContent=(String(member.first_name||'U').charAt(0)+String(member.last_name||'').charAt(0)).toUpperCase();renderPerms(m.permission_allow_ids||[]);E('permissionsMode').value=(m.permission_allow_ids||[]).length?'custom':'role'})}}).then(function(){E('loading').style.display='none';E('memberForm').style.display='block'}).catch(function(e){E('loading').textContent='Unable to load team settings.';toast('error',e.message)})}
E('permissionList').addEventListener('change',function(){E('permissionsMode').value='custom';document.querySelectorAll('.tmi-preset').forEach(function(x){x.classList.remove('active')});var c=document.querySelector('[data-preset="custom"]');if(c)c.classList.add('active');countPerms()});document.querySelectorAll('.tmi-preset').forEach(function(x){x.onclick=function(){choosePreset(x.getAttribute('data-preset'))}});
E('avatarInput').addEventListener('change',function(){var f=this.files&&this.files[0];if(!f)return;var r=new FileReader();r.onload=function(){E('avatarPreview').innerHTML='<img src="'+r.result+'" alt="">'};r.readAsDataURL(f)});
function save(assign,button){if(!E('memberForm').checkValidity()){E('memberForm').reportValidity();return}E('saveAndAssign').value=assign?'1':'0';var fd=new FormData(E('memberForm'));fd.append('csrf_token',csrf);button.disabled=true;button.classList.add('loading');req(fd).then(function(d){toast('success',d.message);setTimeout(function(){window.location.href='team.php'},550)}).catch(function(e){toast('error',e.message);button.disabled=false;button.classList.remove('loading')})}E('saveMember').onclick=function(){save(false,this)};E('saveAssign').onclick=function(){save(true,this)};meta();})();
</script>
<?php require __DIR__ . '/includes/footer.php'; ?>
