<?php
declare(strict_types=1);
ob_start();
ini_set('display_errors','0');
ini_set('html_errors','0');
ini_set('log_errors','1');
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__ . '/../includes/auth.php';
if (session_status() === PHP_SESSION_NONE) { session_start(); }

function auOut($code,$ok,$msg,$extra=array()){while(ob_get_level()>0){@ob_end_clean();}http_response_code($code);header('Content-Type: application/json; charset=utf-8');echo json_encode(array_merge(array('success'=>$ok,'message'=>$msg),$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function auPost($k,$d=''){return isset($_POST[$k])&&!is_array($_POST[$k])?trim((string)$_POST[$k]):$d;}
function auTable(PDO $pdo,$t){$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t");$s->execute(array(':t'=>$t));return (int)$s->fetchColumn()>0;}
function auColumn(PDO $pdo,$t,$c){$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c");$s->execute(array(':t'=>$t,':c'=>$c));return (int)$s->fetchColumn()>0;}
function auJson($s,$default=array()){if(is_array($s))return $s;$x=json_decode((string)$s,true);return is_array($x)?$x:$default;}
function auAudit(PDO $pdo,$tenant,$branch,$user,$action,$id,$old,$new){if(function_exists('tenantAuditLog')){tenantAuditLog($pdo,$action,$tenant,$branch>0?$branch:null,$user,'tenant_automation',$id,$old,$new);}}
function auRequireSchema(PDO $pdo){foreach(array('platform_automation_entities','platform_automation_triggers','platform_automation_conditions','platform_automation_actions','tenant_automations','tenant_automation_conditions','tenant_automation_actions','tenant_automation_runs') as $t){if(!auTable($pdo,$t))auOut(500,false,'Automation database is not installed. Run database/automation-system.sql first.');}}
function auStatuses($entity){if($entity==='quote')return array('draft','awaiting response','changes requested','approved','converted','rejected','expired','archived');if($entity==='invoice')return array('draft','sent','viewed','partially paid','paid','overdue','written off','cancelled','archived');if($entity==='request')return array('new','open','assessment required','quote required','scheduled','closed','cancelled','archived');return array();}
function auTemplates(){return array(
 array('template_key'=>'auto_archive_quotes','entity_key'=>'quote','title'=>'Auto-archive Quotes','trigger_key'=>'quote.sent','relation'=>'after','offset'=>90,'conditions'=>array(array('condition_key'=>'status','operator_key'=>'is_not','value_text'=>'converted')),'actions'=>array(array('action_key'=>'update_status','value_text'=>'archived')),'action_key'=>'update_status'),
 array('template_key'=>'quote_followup_5','entity_key'=>'quote','title'=>'Follow-up with customers 5 days after quotes are sent','trigger_key'=>'quote.sent','relation'=>'after','offset'=>5,'conditions'=>array(array('condition_key'=>'status','operator_key'=>'is_not','value_text'=>'approved')),'actions'=>array(array('action_key'=>'notify','config'=>array('channel'=>'email','recipient'=>'client','subject'=>'Following up on your quote','message'=>'Hi {{customer_name}},\n\nWe are following up on quote {{document_no}}. Please let us know if you have any questions.\n\nThank you,\n{{company_name}}'))),'action_key'=>'notify'),
 array('template_key'=>'quote_followup_2','entity_key'=>'quote','title'=>'Follow-up with customers 2 days after quotes are sent','trigger_key'=>'quote.sent','relation'=>'after','offset'=>2,'conditions'=>array(),'actions'=>array(array('action_key'=>'notify','config'=>array('channel'=>'email','recipient'=>'client','subject'=>'Your quote from {{company_name}}','message'=>'Hi {{customer_name}},\n\nJust checking in about quote {{document_no}}. We are happy to help with any questions.\n\n{{company_name}}'))),'action_key'=>'notify'),
 array('template_key'=>'invoice_due_today','entity_key'=>'invoice','title'=>'Follow-up with customers on the day invoices are due','trigger_key'=>'invoice.due','relation'=>'on','offset'=>0,'conditions'=>array(array('condition_key'=>'status','operator_key'=>'is_not','value_text'=>'paid')),'actions'=>array(array('action_key'=>'notify','config'=>array('channel'=>'email','recipient'=>'client','subject'=>'Invoice {{document_no}} is due today','message'=>'Hi {{customer_name}},\n\nThis is a reminder that invoice {{document_no}} is due today.\n\nThank you,\n{{company_name}}'))),'action_key'=>'notify'),
 array('template_key'=>'invoice_overdue_3','entity_key'=>'invoice','title'=>'Follow-up with customers 3 days after invoices are due','trigger_key'=>'invoice.due','relation'=>'after','offset'=>3,'conditions'=>array(array('condition_key'=>'status','operator_key'=>'is_not','value_text'=>'paid')),'actions'=>array(array('action_key'=>'notify','config'=>array('channel'=>'email','recipient'=>'client','subject'=>'Reminder: invoice {{document_no}} is overdue','message'=>'Hi {{customer_name}},\n\nInvoice {{document_no}} is now overdue. Please arrange payment when possible.\n\nThank you,\n{{company_name}}'))),'action_key'=>'notify'),
 array('template_key'=>'auto_archive_requests','entity_key'=>'request','title'=>'Auto-archive Requests','trigger_key'=>'request.created','relation'=>'after','offset'=>90,'conditions'=>array(array('condition_key'=>'status','operator_key'=>'is','value_text'=>'closed')),'actions'=>array(array('action_key'=>'update_status','value_text'=>'archived')),'action_key'=>'update_status')
 );}
function auMapDisplayStatus($entity,$value){$v=strtolower(trim((string)$value));$v=str_replace(' ','_',$v);if($entity==='quote'&&$v==='awaiting_response')return 'sent';if($entity==='quote'&&$v==='changes_requested')return 'changes_requested';if($entity==='invoice'&&$v==='partially_paid')return 'partially_paid';if($entity==='invoice'&&$v==='written_off')return 'written_off';if($entity==='request'&&$v==='assessment_required')return 'assessment_required';if($entity==='request'&&$v==='quote_required')return 'quote_required';return $v;}

if($_SERVER['REQUEST_METHOD']!=='POST')auOut(405,false,'Method not allowed.');
$token=auPost('csrf_token');if(empty($_SESSION['automations_csrf'])||!is_string($_SESSION['automations_csrf'])||$token===''||!hash_equals($_SESSION['automations_csrf'],$token))auOut(419,false,'Your form session expired. Refresh the page and try again.');
$tenant=(int)$currentTenantId;$branch=(int)$currentBranchId;$user=(int)$currentTenantUserId;$action=auPost('action');
try{
 auRequireSchema($pdo);
 if($action==='bootstrap'){
  $entities=$pdo->query("SELECT id,entity_key,entity_name,source_table FROM platform_automation_entities WHERE is_active=1 AND is_visible=1 ORDER BY sort_order,id")->fetchAll(PDO::FETCH_ASSOC);
  $tr=$pdo->query("SELECT * FROM platform_automation_triggers WHERE is_active=1 AND is_visible=1 ORDER BY entity_key,sort_order,id")->fetchAll(PDO::FETCH_ASSOC);
  $co=$pdo->query("SELECT * FROM platform_automation_conditions WHERE is_active=1 AND is_visible=1 ORDER BY entity_key,sort_order,id")->fetchAll(PDO::FETCH_ASSOC);
  $ac=$pdo->query("SELECT * FROM platform_automation_actions WHERE is_active=1 AND is_visible=1 ORDER BY entity_key,sort_order,id")->fetchAll(PDO::FETCH_ASSOC);
  $tags=array();if(auTable($pdo,'client_tags')){$s=$pdo->prepare("SELECT id,name FROM client_tags WHERE tenant_id=:t AND is_active=1 ORDER BY name");$s->execute(array(':t'=>$tenant));$tags=$s->fetchAll(PDO::FETCH_ASSOC);}
  $items=array();if(auTable($pdo,'product_services')){$where=auColumn($pdo,'product_services','deleted_at')?' AND deleted_at IS NULL':'';$s=$pdo->prepare("SELECT id,name,item_type FROM product_services WHERE tenant_id=:t AND status='active' $where ORDER BY name");$s->execute(array(':t'=>$tenant));$items=$s->fetchAll(PDO::FETCH_ASSOC);}
  $s=$pdo->prepare("SELECT a.*,t.trigger_name,COALESCE((SELECT aa.action_key FROM tenant_automation_actions ta JOIN platform_automation_actions aa ON aa.id=ta.action_id WHERE ta.automation_id=a.id AND ta.tenant_id=a.tenant_id ORDER BY ta.sort_order,ta.id LIMIT 1),'') primary_action_key FROM tenant_automations a JOIN platform_automation_triggers t ON t.id=a.trigger_id WHERE a.tenant_id=:t ORDER BY a.entity_key,a.updated_at DESC,a.id DESC");$s->execute(array(':t'=>$tenant));$autos=$s->fetchAll(PDO::FETCH_ASSOC);
  auOut(200,true,'Automations loaded.',array('meta'=>array('entities'=>$entities,'triggers'=>$tr,'conditions'=>$co,'actions'=>$ac,'tags'=>$tags,'line_items'=>$items,'statuses'=>array('quote'=>auStatuses('quote'),'invoice'=>auStatuses('invoice'),'request'=>auStatuses('request')),'templates'=>auTemplates()),'automations'=>$autos));
 }
 if($action==='get'){
  $id=(int)auPost('automation_id','0');$s=$pdo->prepare("SELECT a.*,t.trigger_name,t.trigger_key FROM tenant_automations a JOIN platform_automation_triggers t ON t.id=a.trigger_id WHERE a.id=:id AND a.tenant_id=:t LIMIT 1");$s->execute(array(':id'=>$id,':t'=>$tenant));$a=$s->fetch(PDO::FETCH_ASSOC);if(!$a)auOut(404,false,'Automation not found.');
  $s=$pdo->prepare("SELECT c.*,m.condition_key,m.condition_name,m.value_source,m.allowed_operators_json FROM tenant_automation_conditions c JOIN platform_automation_conditions m ON m.id=c.condition_id WHERE c.automation_id=:id AND c.tenant_id=:t ORDER BY c.sort_order,c.id");$s->execute(array(':id'=>$id,':t'=>$tenant));$a['conditions']=$s->fetchAll(PDO::FETCH_ASSOC);
  $s=$pdo->prepare("SELECT x.*,m.action_key,m.action_name,m.value_source FROM tenant_automation_actions x JOIN platform_automation_actions m ON m.id=x.action_id WHERE x.automation_id=:id AND x.tenant_id=:t ORDER BY x.sort_order,x.id");$s->execute(array(':id'=>$id,':t'=>$tenant));$acts=$s->fetchAll(PDO::FETCH_ASSOC);foreach($acts as &$r){$r['config']=auJson($r['config_json'],array());}unset($r);$a['actions']=$acts;auOut(200,true,'Automation loaded.',array('automation'=>$a));
 }
 if($action==='save'){
  $id=(int)auPost('automation_id','0');$payload=auJson(auPost('payload'),array());$title=trim((string)($payload['title']??''));$entity=trim((string)($payload['entity_key']??''));$triggerId=(int)($payload['trigger_id']??0);$relation=(string)($payload['trigger_relation']??'after');$offset=max(0,min(3650,(int)($payload['trigger_offset_value']??0)));$isActive=!empty($payload['is_active'])?1:0;$template=isset($payload['template_key'])&&$payload['template_key']!==''?(string)$payload['template_key']:null;$conds=isset($payload['conditions'])&&is_array($payload['conditions'])?$payload['conditions']:array();$acts=isset($payload['actions'])&&is_array($payload['actions'])?$payload['actions']:array();
  if($title==='')auOut(422,false,'Automation title is required.');if(!in_array($relation,array('before','on','after'),true))auOut(422,false,'Invalid trigger timing.');if(!$acts)auOut(422,false,'Add at least one action.');
  $q=$pdo->prepare("SELECT * FROM platform_automation_triggers WHERE id=:id AND entity_key=:e AND is_active=1 AND is_visible=1 LIMIT 1");$q->execute(array(':id'=>$triggerId,':e'=>$entity));$tm=$q->fetch(PDO::FETCH_ASSOC);if(!$tm)auOut(422,false,'Select a valid trigger.');if($relation==='before'&&!$tm['supports_before'])auOut(422,false,'This trigger does not support before timing.');if($relation==='on'&&!$tm['supports_on'])auOut(422,false,'This trigger does not support same-day timing.');if($relation==='after'&&!$tm['supports_after'])auOut(422,false,'This trigger does not support after timing.');
  foreach($conds as &$c){$cm=$pdo->prepare("SELECT * FROM platform_automation_conditions WHERE id=:id AND entity_key=:e AND is_active=1 AND is_visible=1");$cm->execute(array(':id'=>(int)($c['condition_id']??0),':e'=>$entity));$mr=$cm->fetch(PDO::FETCH_ASSOC);if(!$mr)auOut(422,false,'A selected condition is unavailable.');$ops=auJson($mr['allowed_operators_json'],array());if(!in_array((string)($c['operator_key']??''),$ops,true))auOut(422,false,'Invalid condition operator.');if($mr['value_source']==='status')$c['value_text']=auMapDisplayStatus($entity,$c['value_text']??'');}unset($c);
  foreach($acts as &$a){$am=$pdo->prepare("SELECT * FROM platform_automation_actions WHERE id=:id AND entity_key=:e AND is_active=1 AND is_visible=1");$am->execute(array(':id'=>(int)($a['action_id']??0),':e'=>$entity));$mr=$am->fetch(PDO::FETCH_ASSOC);if(!$mr)auOut(422,false,'A selected action is unavailable.');if($mr['action_key']==='update_status')$a['value_text']=auMapDisplayStatus($entity,$a['value_text']??'');if($mr['action_key']==='notify'){if(empty($a['config'])||trim((string)($a['config']['message']??''))==='')auOut(422,false,'Notification message is required.');}}unset($a);
  $pdo->beginTransaction();$old=null;
  if($id>0){$s=$pdo->prepare("SELECT * FROM tenant_automations WHERE id=:id AND tenant_id=:t FOR UPDATE");$s->execute(array(':id'=>$id,':t'=>$tenant));$old=$s->fetch(PDO::FETCH_ASSOC);if(!$old){$pdo->rollBack();auOut(404,false,'Automation not found.');}$s=$pdo->prepare("UPDATE tenant_automations SET title=:title,entity_key=:e,trigger_id=:tr,trigger_relation=:rel,trigger_offset_value=:off,is_active=:active,template_key=:tpl,updated_by=:u,updated_at=NOW() WHERE id=:id AND tenant_id=:t");$s->execute(array(':title'=>$title,':e'=>$entity,':tr'=>$triggerId,':rel'=>$relation,':off'=>$offset,':active'=>$isActive,':tpl'=>$template,':u'=>$user,':id'=>$id,':t'=>$tenant));$pdo->prepare("DELETE FROM tenant_automation_conditions WHERE automation_id=:id AND tenant_id=:t")->execute(array(':id'=>$id,':t'=>$tenant));$pdo->prepare("DELETE FROM tenant_automation_actions WHERE automation_id=:id AND tenant_id=:t")->execute(array(':id'=>$id,':t'=>$tenant));}
  else{$s=$pdo->prepare("INSERT INTO tenant_automations(tenant_id,branch_id,title,entity_key,trigger_id,trigger_relation,trigger_offset_value,trigger_offset_unit,is_active,template_key,created_by,updated_by) VALUES(:t,:b,:title,:e,:tr,:rel,:off,'days',:active,:tpl,:u,:u)");$s->execute(array(':t'=>$tenant,':b'=>$branch>0?$branch:null,':title'=>$title,':e'=>$entity,':tr'=>$triggerId,':rel'=>$relation,':off'=>$offset,':active'=>$isActive,':tpl'=>$template,':u'=>$user));$id=(int)$pdo->lastInsertId();}
  $ci=$pdo->prepare("INSERT INTO tenant_automation_conditions(tenant_id,automation_id,condition_id,operator_key,value_id,value_text,value_json,sort_order) VALUES(:t,:a,:c,:op,:vid,:vtext,:vjson,:sort)");foreach($conds as $i=>$c){$ci->execute(array(':t'=>$tenant,':a'=>$id,':c'=>(int)$c['condition_id'],':op'=>(string)$c['operator_key'],':vid'=>!empty($c['value_id'])?(int)$c['value_id']:null,':vtext'=>isset($c['value_text'])&&$c['value_text']!==''?(string)$c['value_text']:null,':vjson'=>isset($c['value_json'])?json_encode($c['value_json']):null,':sort'=>$i));}
  $ai=$pdo->prepare("INSERT INTO tenant_automation_actions(tenant_id,automation_id,action_id,value_id,value_text,config_json,sort_order) VALUES(:t,:a,:act,:vid,:vtext,:cfg,:sort)");foreach($acts as $i=>$a){$ai->execute(array(':t'=>$tenant,':a'=>$id,':act'=>(int)$a['action_id'],':vid'=>!empty($a['value_id'])?(int)$a['value_id']:null,':vtext'=>isset($a['value_text'])&&$a['value_text']!==''?(string)$a['value_text']:null,':cfg'=>json_encode(isset($a['config'])&&is_array($a['config'])?$a['config']:array(),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':sort'=>$i));}
  $pdo->commit();auAudit($pdo,$tenant,$branch,$user,$old?'AUTOMATION_UPDATED':'AUTOMATION_CREATED',$id,$old,array('title'=>$title,'entity_key'=>$entity,'trigger_id'=>$triggerId,'relation'=>$relation,'offset'=>$offset,'is_active'=>$isActive));auOut(200,true,$old?'Automation updated successfully.':'Automation created successfully.',array('automation_id'=>$id));
 }
 if($action==='toggle'){$id=(int)auPost('automation_id','0');$active=auPost('is_active','0')==='1'?1:0;$s=$pdo->prepare("UPDATE tenant_automations SET is_active=:a,updated_by=:u,updated_at=NOW() WHERE id=:id AND tenant_id=:t");$s->execute(array(':a'=>$active,':u'=>$user,':id'=>$id,':t'=>$tenant));if(!$s->rowCount())auOut(404,false,'Automation not found.');auAudit($pdo,$tenant,$branch,$user,$active?'AUTOMATION_ENABLED':'AUTOMATION_DISABLED',$id,null,array('is_active'=>$active));auOut(200,true,$active?'Automation enabled.':'Automation disabled.');}
 if($action==='delete'){$id=(int)auPost('automation_id','0');$s=$pdo->prepare("DELETE FROM tenant_automations WHERE id=:id AND tenant_id=:t");$s->execute(array(':id'=>$id,':t'=>$tenant));if(!$s->rowCount())auOut(404,false,'Automation not found.');auAudit($pdo,$tenant,$branch,$user,'AUTOMATION_DELETED',$id,null,null);auOut(200,true,'Automation deleted successfully.');}
 auOut(400,false,'Invalid action.');
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('FieldPlx automations API: '.$e->getMessage());auOut(500,false,'Unable to complete the automation request.');}
