<?php
ob_start();
ini_set('display_errors','0');ini_set('html_errors','0');ini_set('log_errors','1');
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__ . '/../includes/auth.php';
if(file_exists(__DIR__.'/../includes/audit.php'))require_once __DIR__.'/../includes/audit.php';

function cr($s,$ok,$m,$x=array()){while(ob_get_level()>0)@ob_end_clean();http_response_code((int)$s);echo json_encode(array_merge(array('success'=>(bool)$ok,'message'=>(string)$m),$x),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function cp($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function cj($v){$j=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);return $j===false?null:$j;}
function tableExists(PDO $pdo,$table){$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:n");$s->execute(array(':n'=>$table));return (int)$s->fetchColumn()>0;}
function columnExists(PDO $pdo,$table,$column){$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c");$s->execute(array(':t'=>$table,':c'=>$column));return (int)$s->fetchColumn()>0;}
function getClient(PDO $pdo,$t,$id){$q=$pdo->prepare("SELECT c.* FROM clients c WHERE c.id=:id AND c.tenant_id=:t AND c.deleted_at IS NULL LIMIT 1");$q->execute(array(':id'=>$id,':t'=>$t));$r=$q->fetch();if(!$r)cr(404,false,'Client not found.');return $r;}
function getPortal(PDO $pdo,$t,$clientId){if(!tableExists($pdo,'client_portal_users'))return null;$hasPhone=columnExists($pdo,'client_portal_users','phone');$sql="SELECT id,email,".($hasPhone?'phone':'NULL AS phone').",status,password_hash FROM client_portal_users WHERE tenant_id=:t AND client_id=:c AND contact_id IS NULL ORDER BY id LIMIT 1";$q=$pdo->prepare($sql);$q->execute(array(':t'=>$t,':c'=>$clientId));$r=$q->fetch();return $r?$r:null;}
function meta(PDO $pdo,$t){$b=$pdo->prepare("SELECT id,name,branch_code FROM branches WHERE tenant_id=:t AND status='active' ORDER BY is_head_office DESC,name");$b->execute(array(':t'=>$t));$u=$pdo->prepare("SELECT id,CONCAT(first_name,CASE WHEN last_name IS NOT NULL AND last_name<>'' THEN CONCAT(' ',last_name) ELSE '' END) name,employee_code,job_title FROM users WHERE tenant_id=:t AND status='active' AND deleted_at IS NULL ORDER BY first_name,last_name");$u->execute(array(':t'=>$t));return array('branches'=>$b->fetchAll(),'users'=>$u->fetchAll());}
function validId(PDO $pdo,$table,$t,$id){if($id<=0)return null;if(!in_array($table,array('branches','users'),true))return null;$sql="SELECT id FROM $table WHERE id=:id AND tenant_id=:t".($table==='users'?" AND status='active' AND deleted_at IS NULL":"")." LIMIT 1";$q=$pdo->prepare($sql);$q->execute(array(':id'=>$id,':t'=>$t));return $q->fetchColumn()?(int)$id:null;}
function activity(PDO $pdo,$t,$b,$u,$event,$id,$title,$details){try{$q=$pdo->prepare("INSERT INTO activity_events(tenant_id,branch_id,actor_user_id,actor_type,event_type,related_type,related_id,client_id,title,details_json,visible_to_client) VALUES(:t,:b,:u,'user',:e,'client',:r,:c,:title,:d,0)");$q->execute(array(':t'=>$t,':b'=>$b>0?$b:null,':u'=>$u,':e'=>substr($event,0,120),':r'=>$id,':c'=>$id,':title'=>substr($title,0,255),':d'=>cj($details)));}catch(Throwable $e){error_log('client activity: '.$e->getMessage());}}
function audit(PDO $pdo,$t,$b,$u,$action,$id,$old,$new){if(function_exists('tenantAuditLog'))tenantAuditLog($pdo,$action,$t,$b,$u,'client',$id,$old,$new);}
function smtpDecrypt($encrypted,$tenantId){$encrypted=trim((string)$encrypted);if($encrypted==='')return '';$raw=base64_decode($encrypted,true);if($raw===false||strlen($raw)<=16)throw new RuntimeException('Stored SMTP password is invalid.');$envKey=getenv('FIELDPLX_APP_KEY');if($envKey===false||trim($envKey)===''){$seed=(defined('DB_NAME')?DB_NAME:'').'|'.(defined('DB_USER')?DB_USER:'').'|'.(defined('DB_PASS')?DB_PASS:'').'|'.(int)$tenantId;}else{$seed=$envKey.'|'.(int)$tenantId;}$key=hash('sha256',$seed,true);$plain=openssl_decrypt(substr($raw,16),'AES-256-CBC',$key,OPENSSL_RAW_DATA,substr($raw,0,16));if($plain===false)throw new RuntimeException('Unable to decrypt SMTP password.');return $plain;}
function smtpRead($socket){$response='';while(!feof($socket)){$line=fgets($socket,515);if($line===false)break;$response.=$line;if(strlen($line)>=4&&$line[3]===' ')break;}return trim($response);}
function smtpCmd($socket,$cmd,$expected,$label){if($cmd!==null&&@fwrite($socket,$cmd."\r\n")===false)throw new RuntimeException('SMTP connection closed while sending '.$label.'.');$res=smtpRead($socket);$code=(int)substr($res,0,3);if(!in_array($code,(array)$expected,true))throw new RuntimeException($label.' failed (SMTP '.$code.'): '.substr(preg_replace('/[\r\n]+/',' ',$res),0,250));return $res;}
function smtpHeader($v){return trim(str_replace(array("\r","\n"),' ',(string)$v));}
function smtpConfig(PDO $pdo,$tenantId,$branchId){if(!tableExists($pdo,'smtp_configurations'))return null;$q=$pdo->prepare("SELECT * FROM smtp_configurations WHERE tenant_id=:t AND is_active=1 AND scope_type IN('tenant','branch') AND (scope_type='tenant' OR (scope_type='branch' AND branch_id=:b)) ORDER BY CASE WHEN scope_type='branch' AND branch_id=:b2 THEN 0 ELSE 1 END,is_default DESC,id DESC LIMIT 1");$q->execute(array(':t'=>$tenantId,':b'=>$branchId>0?$branchId:-1,':b2'=>$branchId>0?$branchId:-1));$r=$q->fetch();return $r?$r:null;}
function smtpSend(array $config,$password,$to,$subject,$html){if(!filter_var($to,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Client email is invalid.');$host=trim((string)$config['host']);$port=(int)$config['port'];$enc=strtolower(trim((string)$config['encryption']));$user=trim((string)$config['username']);$from=trim((string)$config['from_email']);$fromName=trim((string)$config['from_name']);$reply=trim((string)$config['reply_to_email']);if(!filter_var($from,FILTER_VALIDATE_EMAIL))throw new RuntimeException('SMTP From Email is invalid.');$remote=($enc==='ssl'?'ssl://':'tcp://').$host.':'.$port;$ctx=stream_context_create(array('ssl'=>array('verify_peer'=>true,'verify_peer_name'=>true,'allow_self_signed'=>false,'peer_name'=>$host)));$errno=0;$errstr='';$socket=@stream_socket_client($remote,$errno,$errstr,20,STREAM_CLIENT_CONNECT,$ctx);if(!$socket)throw new RuntimeException('Unable to connect to SMTP server: '.($errstr!==''?$errstr:'connection failed').'.');stream_set_timeout($socket,20);try{smtpCmd($socket,null,array(220),'SMTP greeting');$ehlo=!empty($_SERVER['SERVER_NAME'])?preg_replace('/[^A-Za-z0-9.\-]/','',$_SERVER['SERVER_NAME']):'fieldplx.local';if($ehlo==='')$ehlo='fieldplx.local';smtpCmd($socket,'EHLO '.$ehlo,array(250),'EHLO');if($enc==='tls'||$enc==='starttls'){smtpCmd($socket,'STARTTLS',array(220),'STARTTLS');$method=defined('STREAM_CRYPTO_METHOD_TLS_CLIENT')?STREAM_CRYPTO_METHOD_TLS_CLIENT:STREAM_CRYPTO_METHOD_SSLv23_CLIENT;if(@stream_socket_enable_crypto($socket,true,$method)!==true)throw new RuntimeException('Unable to establish TLS encryption.');smtpCmd($socket,'EHLO '.$ehlo,array(250),'EHLO after TLS');}if($user!==''){smtpCmd($socket,'AUTH LOGIN',array(334),'SMTP authentication');smtpCmd($socket,base64_encode($user),array(334),'SMTP username');smtpCmd($socket,base64_encode($password),array(235),'SMTP password');}smtpCmd($socket,'MAIL FROM:<'.$from.'>',array(250),'MAIL FROM');smtpCmd($socket,'RCPT TO:<'.$to.'>',array(250,251),'RCPT TO');smtpCmd($socket,'DATA',array(354),'DATA');$headers=array('Date: '.date(DATE_RFC2822),'From: '.smtpHeader($fromName!==''?$fromName:'FieldPlx').' <'.$from.'>','To: <'.$to.'>','Subject: '.smtpHeader($subject),'MIME-Version: 1.0','Content-Type: text/html; charset=UTF-8','Content-Transfer-Encoding: 8bit');if($reply!==''&&filter_var($reply,FILTER_VALIDATE_EMAIL))$headers[]='Reply-To: <'.$reply.'>';$payload=implode("\r\n",$headers)."\r\n\r\n".$html;$payload=preg_replace('/(?m)^\./','..',$payload);@fwrite($socket,$payload."\r\n.\r\n");smtpCmd($socket,null,array(250),'Message delivery');@fwrite($socket,"QUIT\r\n");}finally{@fclose($socket);}return true;}
function sendClientMail(PDO $pdo,$tenantId,$branchId,$client,$plainPassword,$isEdit,$portalEnabled){$email=trim((string)$client['email']);if($email===''||!filter_var($email,FILTER_VALIDATE_EMAIL))return array('status'=>'skipped','notice'=>'Email not sent because the client has no valid email address.');$config=smtpConfig($pdo,$tenantId,$branchId);if(!$config)return array('status'=>'skipped','notice'=>'Email not sent because Tenant SMTP is not configured or active.');try{$password=smtpDecrypt($config['password_encrypted'],$tenantId);$title=$isEdit?'Your FieldPlx customer account was updated':'Your FieldPlx customer account was created';$loginEmail=trim((string)$client['email']);$loginPhone=trim((string)$client['phone']);$credentials='';if($portalEnabled){$credentials.='<p><strong>Customer Portal Login</strong></p><ul>';if($loginEmail!=='')$credentials.='<li>Email: '.htmlspecialchars($loginEmail,ENT_QUOTES,'UTF-8').'</li>';if($loginPhone!=='')$credentials.='<li>Contact: '.htmlspecialchars($loginPhone,ENT_QUOTES,'UTF-8').'</li>';if($plainPassword!=='')$credentials.='<li>Password: '.htmlspecialchars($plainPassword,ENT_QUOTES,'UTF-8').'</li>';$credentials.='</ul>';if($isEdit&&$plainPassword==='')$credentials.='<p>Your existing password has not been changed.</p>';}else{$credentials='<p>Customer portal login is currently disabled for your account.</p>';}$html='<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#1f2d3d"><h2 style="color:#123d70">'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'</h2><p>Hello '.htmlspecialchars($client['display_name'],ENT_QUOTES,'UTF-8').',</p><p>Your customer profile '.($isEdit?'has been updated successfully.':'has been created successfully.').'</p>'.$credentials.'<p style="margin-top:24px">FieldPlx</p></div>';smtpSend($config,$password,$email,$title,$html);return array('status'=>'sent','notice'=>'Account email sent successfully.');}catch(Throwable $e){error_log('Client account email failed: '.$e->getMessage());return array('status'=>'failed','notice'=>'Client saved, but email failed: '.$e->getMessage());}}

$t=isset($_SESSION['tenant_id'])?(int)$_SESSION['tenant_id']:0;$u=isset($_SESSION['tenant_user_id'])?(int)$_SESSION['tenant_user_id']:0;$b=isset($_SESSION['branch_id'])?(int)$_SESSION['branch_id']:0;if($t<=0||$u<=0)cr(401,false,'Authentication required.');$csrf=(string)cp('csrf_token','');$sc=isset($_SESSION['clients_csrf_token'])?(string)$_SESSION['clients_csrf_token']:'';if($csrf===''||$sc===''||!hash_equals($sc,$csrf))cr(419,false,'Your form session expired. Refresh the page and try again.');$a=trim((string)cp('action',''));
try{
if($a==='meta'){cr(200,true,'Client form data loaded.',array('meta'=>meta($pdo,$t)));}
if($a==='list'){$page=max(1,(int)cp('page',1));$pp=(int)cp('per_page',10);if(!in_array($pp,array(10,25,50),true))$pp=10;$search=trim((string)cp('search',''));$type=trim((string)cp('client_type',''));$status=trim((string)cp('status',''));$bf=(int)cp('branch_id',0);$w=array('c.tenant_id=:t','c.deleted_at IS NULL');$p=array(':t'=>$t);if($search!==''){$sv='%'.$search.'%';$w[]='(c.display_name LIKE :s1 OR c.company_name LIKE :s2 OR c.first_name LIKE :s3 OR c.last_name LIKE :s4 OR c.email LIKE :s5 OR c.phone LIKE :s6 OR c.alternate_phone LIKE :s7 OR c.tax_number LIKE :s8)';for($i=1;$i<=8;$i++)$p[':s'.$i]=$sv;}if(in_array($type,array('lead','client','archived'),true)){$w[]='c.client_type=:ct';$p[':ct']=$type;}if(in_array($status,array('new','active','inactive','archived'),true)){$w[]='c.status=:st';$p[':st']=$status;}if($bf>0){$w[]='c.branch_id=:bf';$p[':bf']=$bf;}$ws=implode(' AND ',$w);$q=$pdo->prepare("SELECT COUNT(*) FROM clients c WHERE $ws");$q->execute($p);$total=(int)$q->fetchColumn();$pages=max(1,(int)ceil($total/$pp));if($page>$pages)$page=$pages;$off=($page-1)*$pp;$sql="SELECT c.id,c.branch_id,c.client_type,c.display_name,c.company_name,c.first_name,c.last_name,c.email,c.phone,c.alternate_phone,c.source,c.preferred_contact_method,c.allow_email,c.allow_sms,c.status,c.tax_number,c.account_manager_id,c.last_activity_at,c.created_at,c.updated_at,b.name branch_name,CONCAT(COALESCE(am.first_name,''),CASE WHEN am.last_name IS NOT NULL AND am.last_name<>'' THEN CONCAT(' ',am.last_name) ELSE '' END) account_manager_name,(SELECT COUNT(*) FROM client_locations cl WHERE cl.tenant_id=c.tenant_id AND cl.client_id=c.id AND cl.deleted_at IS NULL) location_count FROM clients c LEFT JOIN branches b ON b.id=c.branch_id AND b.tenant_id=c.tenant_id LEFT JOIN users am ON am.id=c.account_manager_id AND am.tenant_id=c.tenant_id WHERE $ws ORDER BY FIELD(c.status,'active','new','inactive','archived'),c.display_name LIMIT ".(int)$pp." OFFSET ".(int)$off;$q=$pdo->prepare($sql);$q->execute($p);$rows=$q->fetchAll();$s=$pdo->prepare("SELECT COUNT(*) total,SUM(CASE WHEN client_type='client' AND status='active' THEN 1 ELSE 0 END) clients,SUM(CASE WHEN client_type='lead' AND status<>'archived' THEN 1 ELSE 0 END) leads,COUNT(DISTINCT branch_id) branches FROM clients WHERE tenant_id=:t AND deleted_at IS NULL");$s->execute(array(':t'=>$t));$sm=$s->fetch();cr(200,true,'Clients loaded.',array('clients'=>$rows,'meta'=>meta($pdo,$t),'summary'=>array('total'=>(int)($sm['total']?$sm['total']:0),'clients'=>(int)($sm['clients']?$sm['clients']:0),'leads'=>(int)($sm['leads']?$sm['leads']:0),'branches'=>(int)($sm['branches']?$sm['branches']:0)),'pagination'=>array('page'=>$page,'per_page'=>$pp,'total'=>$total,'pages'=>$pages,'from'=>$total>0?$off+1:0,'to'=>$total>0?min($off+count($rows),$total):0)));}
if($a==='get'){$id=(int)cp('client_id',0);if($id<=0)cr(422,false,'Invalid client.');$portal=getPortal($pdo,$t,$id);cr(200,true,'Client loaded.',array('client'=>getClient($pdo,$t,$id),'portal'=>array('exists'=>$portal?true:false,'email'=>$portal?$portal['email']:null,'phone'=>$portal?$portal['phone']:null,'status'=>$portal?$portal['status']:null),'meta'=>meta($pdo,$t)));}
if($a==='save'){
  if(!tableExists($pdo,'client_portal_users')||!columnExists($pdo,'client_portal_users','phone'))cr(500,false,'Customer portal login update is required. Run migration_client_portal_login.sql once.');
  $id=(int)cp('client_id',0);$type=trim((string)cp('client_type','lead'));$display=trim((string)cp('display_name',''));$company=trim((string)cp('company_name',''));$first=trim((string)cp('first_name',''));$last=trim((string)cp('last_name',''));$email=strtolower(trim((string)cp('email','')));$phone=trim((string)cp('phone',''));$alt=trim((string)cp('alternate_phone',''));$source=trim((string)cp('source',''));$pref=trim((string)cp('preferred_contact_method','email'));$status=trim((string)cp('status','new'));$tax=trim((string)cp('tax_number',''));$notes=trim((string)cp('notes',''));$branch=validId($pdo,'branches',$t,(int)cp('branch_id',0));$manager=validId($pdo,'users',$t,(int)cp('account_manager_id',0));$allowEmail=cp('allow_email','')!==''?1:0;$allowSms=cp('allow_sms','')!==''?1:0;$portalEnabled=cp('portal_enabled','')!=='';$plainPassword=(string)cp('customer_password','');$confirm=(string)cp('confirm_password','');
  if($display==='')cr(422,false,'Display name is required.');if(!in_array($type,array('lead','client','archived'),true))cr(422,false,'Invalid client type.');if(!in_array($status,array('new','active','inactive','archived'),true))cr(422,false,'Invalid client status.');if(!in_array($pref,array('email','sms','phone','whatsapp','none'),true))cr(422,false,'Invalid preferred contact method.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))cr(422,false,'Enter a valid email address.');if($portalEnabled&&$email===''&&$phone==='')cr(422,false,'Enter an email or contact number for customer login.');if($plainPassword!==$confirm)cr(422,false,'Customer password and confirm password do not match.');if($plainPassword!==''&&strlen($plainPassword)<8)cr(422,false,'Customer password must be at least 8 characters.');
  if($email!==''){$sql="SELECT id FROM clients WHERE tenant_id=:t AND email=:e AND deleted_at IS NULL";$pp=array(':t'=>$t,':e'=>$email);if($id>0){$sql.=' AND id<>:id';$pp[':id']=$id;}$q=$pdo->prepare($sql);$q->execute($pp);if($q->fetchColumn())cr(409,false,'This email is already used by another client.');}
  $old=$id>0?getClient($pdo,$t,$id):null;$portalOld=$id>0?getPortal($pdo,$t,$id):null;if(!$old&&$portalEnabled&&$plainPassword==='')cr(422,false,'Customer password is required for a new client login.');if($old&&$portalEnabled&&!$portalOld&&$plainPassword==='')cr(422,false,'Set a customer password to enable portal login for this client.');
  $portalId=$portalOld?(int)$portalOld['id']:0;if($email!==''){$q=$pdo->prepare("SELECT id FROM client_portal_users WHERE tenant_id=:t AND email=:e AND id<>:id LIMIT 1");$q->execute(array(':t'=>$t,':e'=>$email,':id'=>$portalId));if($q->fetchColumn())cr(409,false,'This email is already used for another customer portal login.');}if($phone!==''){$q=$pdo->prepare("SELECT id FROM client_portal_users WHERE tenant_id=:t AND phone=:p AND id<>:id LIMIT 1");$q->execute(array(':t'=>$t,':p'=>$phone,':id'=>$portalId));if($q->fetchColumn())cr(409,false,'This contact number is already used for another customer portal login.');}
  $vals=array(':branch'=>$branch,':type'=>$type,':display'=>$display,':company'=>$company!==''?$company:null,':first'=>$first!==''?$first:null,':last'=>$last!==''?$last:null,':email'=>$email!==''?$email:null,':phone'=>$phone!==''?$phone:null,':alt'=>$alt!==''?$alt:null,':source'=>$source!==''?$source:null,':pref'=>$pref,':ae'=>$allowEmail,':as'=>$allowSms,':status'=>$status,':tax'=>$tax!==''?$tax:null,':notes'=>$notes!==''?$notes:null,':manager'=>$manager);
  $pdo->beginTransaction();try{if($id>0){$vals[':id']=$id;$vals[':t']=$t;$q=$pdo->prepare("UPDATE clients SET branch_id=:branch,client_type=:type,display_name=:display,company_name=:company,first_name=:first,last_name=:last,email=:email,phone=:phone,alternate_phone=:alt,source=:source,preferred_contact_method=:pref,allow_email=:ae,allow_sms=:as,status=:status,tax_number=:tax,notes=:notes,account_manager_id=:manager WHERE id=:id AND tenant_id=:t AND deleted_at IS NULL");$q->execute($vals);}else{$vals[':t']=$t;$vals[':created']=$u;$q=$pdo->prepare("INSERT INTO clients(tenant_id,branch_id,client_type,display_name,company_name,first_name,last_name,email,phone,alternate_phone,source,preferred_contact_method,allow_email,allow_sms,status,tax_number,notes,account_manager_id,created_by) VALUES(:t,:branch,:type,:display,:company,:first,:last,:email,:phone,:alt,:source,:pref,:ae,:as,:status,:tax,:notes,:manager,:created)");$q->execute($vals);$id=(int)$pdo->lastInsertId();}
    $portalStatus=$portalEnabled?'active':'inactive';$hash=$plainPassword!==''?password_hash($plainPassword,PASSWORD_DEFAULT):null;if($portalOld){$sql="UPDATE client_portal_users SET email=:email,phone=:phone,status=:status";$params=array(':email'=>$email!==''?$email:null,':phone'=>$phone!==''?$phone:null,':status'=>$portalStatus,':id'=>$portalOld['id'],':t'=>$t);if($hash!==null){$sql.=",password_hash=:hash";$params[':hash']=$hash;}$sql.=" WHERE id=:id AND tenant_id=:t";$q=$pdo->prepare($sql);$q->execute($params);}else{$q=$pdo->prepare("INSERT INTO client_portal_users(tenant_id,client_id,contact_id,email,phone,password_hash,status) VALUES(:t,:c,NULL,:email,:phone,:hash,:status)");$q->execute(array(':t'=>$t,':c'=>$id,':email'=>$email!==''?$email:null,':phone'=>$phone!==''?$phone:null,':hash'=>$hash,':status'=>$portalStatus));}
    $pdo->commit();
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
  $new=getClient($pdo,$t,$id);activity($pdo,$t,$b,$u,$old?'client_updated':'client_created',$id,($old?'Client updated: ':'Client created: ').$display,array('client'=>$new,'portal_enabled'=>$portalEnabled));audit($pdo,$t,$b,$u,$old?'CLIENT_UPDATED':'CLIENT_CREATED',$id,$old,$new);$mail=sendClientMail($pdo,$t,$branch?$branch:$b,$new,$plainPassword,$old?true:false,$portalEnabled);cr(200,true,$old?'Client updated successfully.':'Client created successfully.',array('client_id'=>$id,'email_status'=>$mail['status'],'email_notice'=>$mail['notice']));
}
if($a==='change_status'){$id=(int)cp('client_id',0);$status=trim((string)cp('status',''));if(!in_array($status,array('new','active','inactive','archived'),true))cr(422,false,'Invalid client status.');$old=getClient($pdo,$t,$id);$type=$status==='archived'?'archived':$old['client_type'];$q=$pdo->prepare("UPDATE clients SET status=:s,client_type=:ct WHERE id=:id AND tenant_id=:t AND deleted_at IS NULL");$q->execute(array(':s'=>$status,':ct'=>$type,':id'=>$id,':t'=>$t));$new=getClient($pdo,$t,$id);activity($pdo,$t,$b,$u,'client_status_changed',$id,'Client status changed: '.$new['display_name'],array('old_status'=>$old['status'],'new_status'=>$new['status']));audit($pdo,$t,$b,$u,'CLIENT_STATUS_CHANGED',$id,array('status'=>$old['status']),array('status'=>$new['status']));cr(200,true,'Client status updated successfully.');}
if($a==='archive'||$a==='delete'){$id=(int)cp('client_id',0);$old=getClient($pdo,$t,$id);$pdo->beginTransaction();try{$q=$pdo->prepare("UPDATE clients SET client_type='archived',status='archived',deleted_at=NOW() WHERE id=:id AND tenant_id=:t AND deleted_at IS NULL");$q->execute(array(':id'=>$id,':t'=>$t));if(tableExists($pdo,'client_portal_users')){$q=$pdo->prepare("UPDATE client_portal_users SET status='inactive' WHERE tenant_id=:t AND client_id=:c");$q->execute(array(':t'=>$t,':c'=>$id));}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}$del=$a==='delete';activity($pdo,$t,$b,$u,$del?'client_deleted':'client_archived',$id,($del?'Client deleted: ':'Client archived: ').$old['display_name'],$old);audit($pdo,$t,$b,$u,$del?'CLIENT_DELETED':'CLIENT_ARCHIVED',$id,$old,array('client_type'=>'archived','status'=>'archived','deleted_at'=>date('Y-m-d H:i:s')));cr(200,true,$del?'Client deleted successfully.':'Client archived successfully.');}
cr(400,false,'Unsupported clients action.');
}catch(PDOException $e){error_log('FieldPlx clients PDO error: '.$e->getMessage());if(isset($e->errorInfo[1])&&(int)$e->errorInfo[1]===1062)cr(409,false,'Email or contact number is already used by another customer login.');cr(500,false,'Unable to process the clients request.');}catch(Throwable $e){error_log('FieldPlx clients API error: '.$e->getMessage());cr(500,false,$e->getMessage());}
