<?php
/* FieldPlx Product Form API - Version 2.0.1 - 2026-08-29 */
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/db.php';
if (session_status() === PHP_SESSION_NONE) session_start();
header('Content-Type: application/json; charset=utf-8');

function pfOut($status,$success,$message,$extra=array()){http_response_code((int)$status);echo json_encode(array_merge(array('success'=>(bool)$success,'message'=>(string)$message),$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function pfDb(){global $pdo,$db;if(isset($pdo)&&$pdo instanceof PDO)return $pdo;if(isset($db)&&$db instanceof PDO)return $db;throw new RuntimeException('PDO database connection is not available.');}
function pfTenantId(){if(!empty($_SESSION['tenant_id']))return (int)$_SESSION['tenant_id'];if(!empty($_SESSION['business_id']))return (int)$_SESSION['business_id'];return 0;}
function pfUserId(){if(!empty($_SESSION['tenant_user_id']))return (int)$_SESSION['tenant_user_id'];if(!empty($_SESSION['user_id']))return (int)$_SESSION['user_id'];return 0;}
function pfBranchId(){if(!empty($_SESSION['branch_id']))return (int)$_SESSION['branch_id'];if(!empty($_SESSION['tenant_branch_id']))return (int)$_SESSION['tenant_branch_id'];return 0;}
function pfTable(PDO $pdo,$name){$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:n");$s->execute(array(':n'=>$name));return (int)$s->fetchColumn()>0;}
function pfTitleCase($value){$value=trim((string)$value);if($value==='')return '';if(function_exists('mb_convert_case'))return mb_convert_case(mb_strtolower($value,'UTF-8'),MB_CASE_TITLE,'UTF-8');return ucwords(strtolower($value));}
function pfSelling($base,$type,$markup){$base=max(0,(float)$base);$markup=max(0,(float)$markup);return round($type==='fixed'?$base+$markup:$base+($base*$markup/100),2);}
function pfUpload($field,$tenantId,$folderName,$prefix){if(!isset($_FILES[$field])||!is_array($_FILES[$field])||(int)$_FILES[$field]['error']===UPLOAD_ERR_NO_FILE)return null;if((int)$_FILES[$field]['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Unable to upload '.$prefix.' image.');if((int)$_FILES[$field]['size']>4*1024*1024)throw new RuntimeException(ucfirst($prefix).' image must be 4 MB or smaller.');$f=new finfo(FILEINFO_MIME_TYPE);$m=$f->file($_FILES[$field]['tmp_name']);$allowed=array('image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp');if(!isset($allowed[$m]))throw new RuntimeException(ucfirst($prefix).' image must be JPG, PNG or WEBP.');$folder='uploads/product-masters/tenant-'.(int)$tenantId.'/'.$folderName;$abs=dirname(__DIR__).'/'.$folder;if(!is_dir($abs)&&!@mkdir($abs,0755,true)&&!is_dir($abs))throw new RuntimeException('Unable to create upload folder.');$file=$prefix.'-'.date('YmdHis').'-'.bin2hex(random_bytes(4)).'.'.$allowed[$m];if(!move_uploaded_file($_FILES[$field]['tmp_name'],$abs.'/'.$file))throw new RuntimeException('Unable to save '.$prefix.' image.');return $folder.'/'.$file;}

try{
$pdo=pfDb();$tenantId=pfTenantId();$userId=pfUserId();$sessionBranchId=pfBranchId();if($tenantId<=0||$userId<=0)pfOut(401,false,'Your login session is not valid.');if($_SERVER['REQUEST_METHOD']!=='POST')pfOut(405,false,'Method not allowed.');$csrf=(string)($_POST['csrf_token']??'');$sc=(string)($_SESSION['product_form_csrf_token']??'');if($csrf===''||$sc===''||!hash_equals($sc,$csrf))pfOut(419,false,'Your form session expired. Refresh the page and try again.');
foreach(array('products','product_categories','units_of_measure','product_tax_rates','product_inventory','product_inventory_movements') as $t){if(!pfTable($pdo,$t))pfOut(500,false,'Product master migration is not installed. Run product-master-migration.sql first.');}
$action=trim((string)($_POST['action']??''));

if($action==='meta'){
  $id=max(0,(int)($_POST['id']??0));
  $c=$pdo->prepare("SELECT id,name,image_path FROM product_categories WHERE tenant_id=:t AND status='active' ORDER BY name");$c->execute(array(':t'=>$tenantId));
  $u=$pdo->prepare("SELECT id,name,symbol,image_path FROM units_of_measure WHERE tenant_id=:t AND status='active' ORDER BY name");$u->execute(array(':t'=>$tenantId));
  $x=$pdo->prepare("SELECT id,tax_name,rate_percent,state_code,state_name,tax_type,jurisdiction_name FROM product_tax_rates WHERE tenant_id=:t AND status='active' ORDER BY tax_name,state_code");$x->execute(array(':t'=>$tenantId));
  $b=$pdo->prepare("SELECT id,name,branch_code FROM branches WHERE tenant_id=:t AND status='active' ORDER BY is_head_office DESC,name");$b->execute(array(':t'=>$tenantId));$branches=$b->fetchAll(PDO::FETCH_ASSOC);
  $product=null;$inventories=array();
  if($id>0){$p=$pdo->prepare("SELECT id,category_id,unit_of_measure_id,tax_id,sku,name,description,image_path,unit_name,base_unit_price,markup_type,markup_value,selling_price,tax_percent,track_inventory,status FROM products WHERE id=:id AND tenant_id=:t AND deleted_at IS NULL LIMIT 1");$p->execute(array(':id'=>$id,':t'=>$tenantId));$product=$p->fetch(PDO::FETCH_ASSOC);if(!$product)pfOut(404,false,'Product not found.');$iv=$pdo->prepare("SELECT branch_id,quantity_on_hand,quantity_reserved,reorder_level,minimum_stock,status FROM product_inventory WHERE tenant_id=:t AND product_id=:p ORDER BY branch_id");$iv->execute(array(':t'=>$tenantId,':p'=>$id));$inventories=$iv->fetchAll(PDO::FETCH_ASSOC);}
  $defaultBranch=$sessionBranchId;if($defaultBranch<=0&&!empty($branches))$defaultBranch=(int)$branches[0]['id'];
  $cq=$pdo->prepare("SELECT c.symbol,c.symbol_position,c.decimal_places,c.currency_code FROM tenants t LEFT JOIN currencies c ON c.id=t.currency_id WHERE t.id=:t LIMIT 1");
  $cq->execute(array(':t'=>$tenantId));
  $currency=$cq->fetch(PDO::FETCH_ASSOC);
  if(!$currency)$currency=array('symbol'=>'','symbol_position'=>'before','decimal_places'=>2,'currency_code'=>'');
  pfOut(200,true,'Product form data loaded.',array('product'=>$product,'meta'=>array('categories'=>$c->fetchAll(PDO::FETCH_ASSOC),'uoms'=>$u->fetchAll(PDO::FETCH_ASSOC),'taxes'=>$x->fetchAll(PDO::FETCH_ASSOC),'branches'=>$branches,'inventories'=>$inventories,'default_branch_id'=>$defaultBranch,'currency'=>array('symbol'=>(string)($currency['symbol']??''),'position'=>(string)($currency['symbol_position']??'before'),'decimals'=>(int)($currency['decimal_places']??2),'code'=>(string)($currency['currency_code']??'')))));
}

if($action==='create_category'){
  $name=pfTitleCase($_POST['name']??'');if($name==='')pfOut(422,false,'Category name is required.');$q=$pdo->prepare("SELECT id,name,image_path FROM product_categories WHERE tenant_id=:t AND name=:n LIMIT 1");$q->execute(array(':t'=>$tenantId,':n'=>$name));$row=$q->fetch(PDO::FETCH_ASSOC);if($row)pfOut(200,true,'Category already exists.',array('master'=>$row));$s=$pdo->prepare("INSERT INTO product_categories(tenant_id,name,status,created_by,created_at,updated_at) VALUES(:t,:n,'active',:u,NOW(),NOW())");$s->execute(array(':t'=>$tenantId,':n'=>$name,':u'=>$userId));pfOut(200,true,'Category created.',array('master'=>array('id'=>(int)$pdo->lastInsertId(),'name'=>$name,'image_path'=>null)));
}
if($action==='create_uom'){
  $name=pfTitleCase($_POST['name']??'');if($name==='')pfOut(422,false,'Unit of measure is required.');$q=$pdo->prepare("SELECT id,name,symbol,image_path FROM units_of_measure WHERE tenant_id=:t AND name=:n LIMIT 1");$q->execute(array(':t'=>$tenantId,':n'=>$name));$row=$q->fetch(PDO::FETCH_ASSOC);if($row)pfOut(200,true,'Unit already exists.',array('master'=>$row));$s=$pdo->prepare("INSERT INTO units_of_measure(tenant_id,name,symbol,status,created_by,created_at,updated_at) VALUES(:t,:n,:s,'active',:u,NOW(),NOW())");$symbol=strlen($name)<=8?$name:null;$s->execute(array(':t'=>$tenantId,':n'=>$name,':s'=>$symbol,':u'=>$userId));pfOut(200,true,'Unit of measure created.',array('master'=>array('id'=>(int)$pdo->lastInsertId(),'name'=>$name,'symbol'=>$symbol,'image_path'=>null)));
}
if($action==='create_tax'){
  $taxName=pfTitleCase($_POST['tax_name']??'');$rate=(float)($_POST['rate_percent']??-1);$stateCode=strtoupper(trim((string)($_POST['state_code']??'')));$taxType=trim((string)($_POST['tax_type']??'state'));$jur=pfTitleCase($_POST['jurisdiction_name']??'');if($taxName==='')pfOut(422,false,'Tax name is required.');if($rate<0||$rate>100)pfOut(422,false,'Tax rate must be between 0 and 100.');if($stateCode!==''&&!preg_match('/^[A-Z]{2}$/',$stateCode))pfOut(422,false,'Select a valid US state.');if(!in_array($taxType,array('state','county','city','special','combined','other'),true))pfOut(422,false,'Invalid tax type.');$stateNames=array('AL'=>'Alabama','AK'=>'Alaska','AZ'=>'Arizona','AR'=>'Arkansas','CA'=>'California','CO'=>'Colorado','CT'=>'Connecticut','DE'=>'Delaware','FL'=>'Florida','GA'=>'Georgia','HI'=>'Hawaii','ID'=>'Idaho','IL'=>'Illinois','IN'=>'Indiana','IA'=>'Iowa','KS'=>'Kansas','KY'=>'Kentucky','LA'=>'Louisiana','ME'=>'Maine','MD'=>'Maryland','MA'=>'Massachusetts','MI'=>'Michigan','MN'=>'Minnesota','MS'=>'Mississippi','MO'=>'Missouri','MT'=>'Montana','NE'=>'Nebraska','NV'=>'Nevada','NH'=>'New Hampshire','NJ'=>'New Jersey','NM'=>'New Mexico','NY'=>'New York','NC'=>'North Carolina','ND'=>'North Dakota','OH'=>'Ohio','OK'=>'Oklahoma','OR'=>'Oregon','PA'=>'Pennsylvania','RI'=>'Rhode Island','SC'=>'South Carolina','SD'=>'South Dakota','TN'=>'Tennessee','TX'=>'Texas','UT'=>'Utah','VT'=>'Vermont','VA'=>'Virginia','WA'=>'Washington','WV'=>'West Virginia','WI'=>'Wisconsin','WY'=>'Wyoming','DC'=>'District Of Columbia');$stateName=$stateCode!==''?($stateNames[$stateCode]??$stateCode):null;$q=$pdo->prepare("SELECT id,tax_name,rate_percent,state_code,state_name,tax_type,jurisdiction_name FROM product_tax_rates WHERE tenant_id=:t AND tax_name=:n AND state_code=:sk AND tax_type=:tt LIMIT 1");$q->execute(array(':t'=>$tenantId,':n'=>$taxName,':sk'=>$stateCode,':tt'=>$taxType));$row=$q->fetch(PDO::FETCH_ASSOC);if($row)pfOut(200,true,'Tax already exists.',array('tax'=>$row));$s=$pdo->prepare("INSERT INTO product_tax_rates(tenant_id,tax_name,rate_percent,country_code,state_code,state_name,tax_type,jurisdiction_name,status,created_by,created_at,updated_at) VALUES(:t,:n,:r,'US',:sc,:sn,:tt,:j,'active',:u,NOW(),NOW())");$s->execute(array(':t'=>$tenantId,':n'=>$taxName,':r'=>number_format($rate,4,'.',''),':sc'=>$stateCode,':sn'=>$stateName,':tt'=>$taxType,':j'=>$jur!==''?$jur:null,':u'=>$userId));pfOut(200,true,'Tax created.',array('tax'=>array('id'=>(int)$pdo->lastInsertId(),'tax_name'=>$taxName,'rate_percent'=>$rate,'state_code'=>$stateCode?:null,'state_name'=>$stateName,'tax_type'=>$taxType,'jurisdiction_name'=>$jur?:null)));
}

if($action==='save_product'){
  $id=max(0,(int)($_POST['id']??0));$name=pfTitleCase($_POST['name']??'');$sku=strtoupper(trim((string)($_POST['sku']??'')));$desc=trim((string)($_POST['description']??''));$categoryId=max(0,(int)($_POST['category_id']??0));$uomId=max(0,(int)($_POST['unit_of_measure_id']??0));$taxId=max(0,(int)($_POST['tax_id']??0));$base=(float)($_POST['base_unit_price']??0);$markupType=trim((string)($_POST['markup_type']??'percentage'));$markup=(float)($_POST['markup_value']??0);$status=trim((string)($_POST['status']??'active'));$track=!empty($_POST['track_inventory'])?1:0;$branchId=max(0,(int)($_POST['inventory_branch_id']??0));$stock=(float)($_POST['stock_quantity']??0);$reorder=max(0,(float)($_POST['reorder_level']??0));$minimum=max(0,(float)($_POST['minimum_stock']??0));
  if($name==='')pfOut(422,false,'Product name is required.');if($uomId<=0)pfOut(422,false,'Unit of measure is required.');if($base<0||$markup<0)pfOut(422,false,'Price and markup cannot be negative.');if(!in_array($markupType,array('percentage','fixed'),true))pfOut(422,false,'Invalid markup type.');if(!in_array($status,array('active','inactive','archived'),true))pfOut(422,false,'Invalid product status.');if($track&&$branchId<=0)pfOut(422,false,'Select an inventory branch.');
  if($sku!==''){$q=$pdo->prepare("SELECT id FROM products WHERE tenant_id=:t AND sku=:s AND deleted_at IS NULL".($id>0?" AND id<>:id":"")." LIMIT 1");$pa=array(':t'=>$tenantId,':s'=>$sku);if($id>0)$pa[':id']=$id;$q->execute($pa);if($q->fetchColumn())pfOut(409,false,'This SKU / product code is already in use.');}
  if($categoryId>0){$q=$pdo->prepare("SELECT id,name FROM product_categories WHERE id=:id AND tenant_id=:t AND status='active' LIMIT 1");$q->execute(array(':id'=>$categoryId,':t'=>$tenantId));if(!$q->fetch())pfOut(422,false,'Selected category is invalid.');}
  $q=$pdo->prepare("SELECT id,name,symbol FROM units_of_measure WHERE id=:id AND tenant_id=:t AND status='active' LIMIT 1");$q->execute(array(':id'=>$uomId,':t'=>$tenantId));$uom=$q->fetch(PDO::FETCH_ASSOC);if(!$uom)pfOut(422,false,'Selected unit is invalid.');$unitName=trim((string)($uom['symbol']?:$uom['name']));
  $taxPercent=0;if($taxId>0){$q=$pdo->prepare("SELECT id,rate_percent FROM product_tax_rates WHERE id=:id AND tenant_id=:t AND status='active' LIMIT 1");$q->execute(array(':id'=>$taxId,':t'=>$tenantId));$tax=$q->fetch(PDO::FETCH_ASSOC);if(!$tax)pfOut(422,false,'Selected tax is invalid.');$taxPercent=(float)$tax['rate_percent'];}
  if($branchId>0){$q=$pdo->prepare("SELECT id FROM branches WHERE id=:id AND tenant_id=:t AND status='active' LIMIT 1");$q->execute(array(':id'=>$branchId,':t'=>$tenantId));if(!$q->fetchColumn())pfOut(422,false,'Selected inventory branch is invalid.');}
  $selling=pfSelling($base,$markupType,$markup);$productImage=pfUpload('product_image',$tenantId,'products','product');$categoryImage=pfUpload('category_image',$tenantId,'categories','category');$uomImage=pfUpload('uom_image',$tenantId,'units','unit');
  $wasEdit = $id > 0;
  $pdo->beginTransaction();
  if($id>0){$q=$pdo->prepare("SELECT id,image_path FROM products WHERE id=:id AND tenant_id=:t AND deleted_at IS NULL LIMIT 1 FOR UPDATE");$q->execute(array(':id'=>$id,':t'=>$tenantId));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old){$pdo->rollBack();pfOut(404,false,'Product not found.');}$image=$productImage!==null?$productImage:$old['image_path'];$s=$pdo->prepare("UPDATE products SET category_id=:c,unit_of_measure_id=:u,tax_id=:tax,sku=:sku,name=:n,description=:d,image_path=:img,unit_name=:un,base_unit_price=:b,markup_type=:mt,markup_value=:mv,selling_price=:sp,tax_percent=:tp,track_inventory=:ti,status=:st,updated_at=NOW() WHERE id=:id AND tenant_id=:t");$s->execute(array(':c'=>$categoryId?:null,':u'=>$uomId,':tax'=>$taxId?:null,':sku'=>$sku?:null,':n'=>$name,':d'=>$desc?:null,':img'=>$image,':un'=>$unitName,':b'=>number_format($base,2,'.',''),':mt'=>$markupType,':mv'=>number_format($markup,2,'.',''),':sp'=>number_format($selling,2,'.',''),':tp'=>number_format($taxPercent,3,'.',''),':ti'=>$track,':st'=>$status,':id'=>$id,':t'=>$tenantId));
  }else{$s=$pdo->prepare("INSERT INTO products(tenant_id,category_id,unit_of_measure_id,tax_id,sku,name,description,image_path,unit_name,base_unit_price,markup_type,markup_value,selling_price,tax_percent,track_inventory,status,created_by,created_at,updated_at,deleted_at) VALUES(:t,:c,:u,:tax,:sku,:n,:d,:img,:un,:b,:mt,:mv,:sp,:tp,:ti,:st,:cb,NOW(),NOW(),NULL)");$s->execute(array(':t'=>$tenantId,':c'=>$categoryId?:null,':u'=>$uomId,':tax'=>$taxId?:null,':sku'=>$sku?:null,':n'=>$name,':d'=>$desc?:null,':img'=>$productImage,':un'=>$unitName,':b'=>number_format($base,2,'.',''),':mt'=>$markupType,':mv'=>number_format($markup,2,'.',''),':sp'=>number_format($selling,2,'.',''),':tp'=>number_format($taxPercent,3,'.',''),':ti'=>$track,':st'=>$status,':cb'=>$userId));$id=(int)$pdo->lastInsertId();}
  if($categoryImage!==null&&$categoryId>0){$q=$pdo->prepare("UPDATE product_categories SET image_path=:p,updated_at=NOW() WHERE id=:id AND tenant_id=:t");$q->execute(array(':p'=>$categoryImage,':id'=>$categoryId,':t'=>$tenantId));}
  if($uomImage!==null&&$uomId>0){$q=$pdo->prepare("UPDATE units_of_measure SET image_path=:p,updated_at=NOW() WHERE id=:id AND tenant_id=:t");$q->execute(array(':p'=>$uomImage,':id'=>$uomId,':t'=>$tenantId));}
  if($track){$q=$pdo->prepare("SELECT id,quantity_on_hand FROM product_inventory WHERE tenant_id=:t AND product_id=:p AND branch_key=:bk LIMIT 1 FOR UPDATE");$q->execute(array(':t'=>$tenantId,':p'=>$id,':bk'=>$branchId));$inv=$q->fetch(PDO::FETCH_ASSOC);if($inv){$oldQty=(float)$inv['quantity_on_hand'];$diff=$stock-$oldQty;$u=$pdo->prepare("UPDATE product_inventory SET branch_id=:b,quantity_on_hand=:q,reorder_level=:r,minimum_stock=:m,status='active',updated_at=NOW() WHERE id=:id");$u->execute(array(':b'=>$branchId,':q'=>number_format($stock,3,'.',''),':r'=>number_format($reorder,3,'.',''),':m'=>number_format($minimum,3,'.',''),':id'=>$inv['id']));if(abs($diff)>0.0000001){$mv=$pdo->prepare("INSERT INTO product_inventory_movements(tenant_id,branch_id,product_id,movement_type,quantity_change,balance_after,reference_type,notes,created_by,created_at) VALUES(:t,:b,:p,'adjustment',:chg,:bal,'product_form','Stock adjusted from product form',:u,NOW())");$mv->execute(array(':t'=>$tenantId,':b'=>$branchId,':p'=>$id,':chg'=>number_format($diff,3,'.',''),':bal'=>number_format($stock,3,'.',''),':u'=>$userId));}}else{$i=$pdo->prepare("INSERT INTO product_inventory(tenant_id,branch_id,product_id,quantity_on_hand,quantity_reserved,reorder_level,minimum_stock,status,created_at,updated_at) VALUES(:t,:b,:p,:q,0,:r,:m,'active',NOW(),NOW())");$i->execute(array(':t'=>$tenantId,':b'=>$branchId,':p'=>$id,':q'=>number_format($stock,3,'.',''),':r'=>number_format($reorder,3,'.',''),':m'=>number_format($minimum,3,'.','')));if(abs($stock)>0.0000001){$mv=$pdo->prepare("INSERT INTO product_inventory_movements(tenant_id,branch_id,product_id,movement_type,quantity_change,balance_after,reference_type,notes,created_by,created_at) VALUES(:t,:b,:p,'opening',:chg,:bal,'product_form','Opening stock',:u,NOW())");$mv->execute(array(':t'=>$tenantId,':b'=>$branchId,':p'=>$id,':chg'=>number_format($stock,3,'.',''),':bal'=>number_format($stock,3,'.',''),':u'=>$userId));}}}else{$q=$pdo->prepare("UPDATE product_inventory SET status='inactive',updated_at=NOW() WHERE tenant_id=:t AND product_id=:p");$q->execute(array(':t'=>$tenantId,':p'=>$id));}
  $pdo->commit();pfOut(200,true,$wasEdit?'Product updated successfully.':'Product created successfully.',array('id'=>$id,'selling_price'=>$selling));
}
pfOut(400,false,'Unknown action.');
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('FieldPlx product form: '.$e->getMessage());pfOut(500,false,'Unable to process the product request. '.$e->getMessage());}
